### ISSUE TITLE
[betterstats-3.7.1+fabric-1.20.4] Instant kick on server that works through velocity

### ISSUE THREAD

**Issue by ItzSkyReed** [TheCSMods/mc-better-stats#103]
### What happened?

During an attempt to connect to a fabric server that runs through velocity, I am instantly got kicked.
 I understand that the paper website itself says that cross stitch is needed for mods to work (which has not been updated to 1.20.x), and this is not exactly a bug. However, for example, [Servux](https://modrinth.com/mod/servux) works despite this. may be you can somehow fix this issue. Without better statistics screen everyting works fine.

### Steps to reproduce

1. run fabric server with FabricProxyLite and Better Statistics Screen
2. Try to connect to velocity
3. Got kicked instantly

### Relevant log output or crash report

[velocity log](https://pastebin.com/fKymrq13)
[server log](https://pastebin.com/T7JhXygw)

### Other installed mods

All the mods are in [server log](https://pastebin.com/T7JhXygw)

### Code of Conduct

- [X] I agree that if the issue is regarding a crash, I gave the logs and the crash report.
- [X] I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.

**Comment by ajh123** [comment]
I'm on 1.20.1 Fabric with betterstats 3.8.1, FabricProxy-Lite-2.6.0 and crossstitch-0.1.6 with Velocity 3.3.0-SNAPSHOT (git-b9b11665-b343) and this mod works fine. Either there is a problem since 1.20.1 or its one of the mods you are using.

My full mod list: 
[mods.txt](https://github.com/TheCSMods/mc-better-stats/files/14260860/mods.txt)

**Comment by ItzSkyReed** [comment]
With cross stich it doesn't kick you, thanks (it wasn't specified that cross stitch is compatible with 1.20.x when I saw, so I thought it didn't work)
but is it really work? Looks like it can't connect to the server. and live hud stats update doesn't work. I also tried without any other mods.
![image](https://github.com/TheCSMods/mc-better-stats/assets/93844414/ee4806f2-2f9c-41bb-9c76-c3e913fb9a0c)

**Comment by ItzSkyReed** [comment]
![image](https://github.com/TheCSMods/mc-better-stats/assets/93844414/32ff4235-3543-41e1-bb3a-116a65f95fb6)
ah, I think it works

**Comment by TheCSDev** [comment]
> With cross stich it doesn't kick you, thanks (it wasn't specified that cross stitch is compatible with 1.20.x when I saw, so I thought it didn't work) but is it really work? Looks like it can't connect to the server. I also tried without any other mods. ![image](https://private-user-images.githubusercontent.com/93844414/304843122-ee4806f2-2f9c-41bb-9c76-c3e913fb9a0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5Mzk0NDEsIm5iZiI6MTcwNzkzOTE0MSwicGF0aCI6Ii85Mzg0NDQxNC8zMDQ4NDMxMjItZWU0ODA2ZjItMmY5Yy00MWJiLTljNzYtYzNlOTEzZmI5YTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDE5MzIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMTRmNDg1ODUxNGUxMDk0MzM3MmFkYzdhZGM1MGYzNzA0ZjBjOWY3MThiMjRhZjYwNzcxNDE2MjA4MGEyOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XJ-hHxUVqXwdFZ58dMiwbSdRnCEkrly38loWi-q7vOg)

Just in case there was any confusion;  
The image shown on the grayed-out button is a pixel-art icon of a "cell tower".
- When the top of this cell tower is grayed out, then the mod is not connected to the betterstats server
- When however, the top of this cell tower is blue, that means the betterstats client already successfully connected to the betterstats server

Given the image shows a cell-tower icon with the blue color on its top, this means the client successfully managed to connect. In `v3.8`, I also made it so the button is grayed-out once the connection is established, as there's no point to disabling it (given the betterstats server already knows you have BSS installed by that point). In other words, a grayed-out button doesn't always mean "can't connect".

Just felt I'd wanna mention all that, just in case, because of the `Looks like it can't connect to the server` part, so as to mitigate any confusion.
