### ISSUE TITLE
[v3.9.6+fabric-1.20.4] Raw translation string under mobs statistics filter

### ISSUE THREAD

**Issue by xxxkingxl** [TheCSMods/mc-better-stats#115]
### What happened?

when viewing the mob statistics I tried to change the order and saw one option in a raw translation string instead of human text

image link essential mod: https://media.essential.gg/e61a4b2f-02e8-4c22-bf53-660982398000
![image](https://github.com/TheCSMods/mc-better-stats/assets/101728597/877cceff-8c3a-4224-9deb-b780a79c722a)

### Steps to reproduce

1. open the statistics menu
2. select mobs in the main filter
3. try to switch order filter
4. u see **the raw translation text**, "Default" and "Died to" (the raw translation text goes off the text box but is not visible out side of the textbox and u see only the first part: "**betterstats.stat_type_phrase.minec**raft...")

### Relevant log output or crash report

```shell
https://paste.atlauncher.com/view/13b46cfc-7370-4199-876d-dfdd22f0f2fe
```

### Other installed mods

1. wurst
2. essential
3. modpack: Fabulously optimized (maybe usefull to know: crowdin translate (included in modpack))
4. a few mod additions that should not be able conflict
5. removed the controller mod and zoom mod (more, idk. I modify modpacks to fit my needs)
6. item swapper
7. lazy language loader
8. not enough crashes
9. no chat reports
10.  starlight
11. very many players
12. Xaero- 's minimap, 's worldmap & plus
13. wakes
14. cubes without borders
15. betterf3
16. A few mod additions that should not be able conflict and idk what I added more
17. A vanilla tweaks texture pack what doesnt conflict with wurst or essential
18. 
![image](https://github.com/TheCSMods/mc-better-stats/assets/101728597/b83a9d2b-c28e-49db-89f1-4354bd41e67d)
![image](https://github.com/TheCSMods/mc-better-stats/assets/101728597/8fd2602a-ec93-4ace-acf9-2d8b3bb5be5b)
![image](https://github.com/TheCSMods/mc-better-stats/assets/101728597/cd4c8ee4-f42d-4b13-a0cd-1fefd2eaa5bc)

### Code of Conduct

- [X] I agree that if the issue is regarding a crash, I gave the logs and the crash report.
- [X] I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.

**Comment by TheCSDev** [comment]
Hello, and thanks for the bug report.  
After looking into it, it appears that the text in question used the wrong translation key (aka `betterstats.stat_type_phrase` instead of `betterstats.stattype_phrase`). It also appears that I accidentally left that out for `1.20.4` only  
![image](https://github.com/TheCSMods/mc-better-stats/assets/66475965/b9bd6a26-364d-4a74-80b4-41a1025c5881)  
Will fix that in the next update tho.

### The crash
Also, as for the crash log you left in this report; It was unnecessary, as the crash was not caused by this mod. After looking into the crash report, it appears that the following line of code  
`gg.essential.gui.screenshot.providers.CloudflareImageProvider.loadImage(CloudflareImageProvider.kt:54)`  
was executed (by I assume "essential"), and it attempted to fetch an image from the internet, as seen here  
`java.io.IOException: Server returned HTTP response code: 403 for URL: https://imagedelivery.net/W9K_l6ndK9x4x8m3rurakg/e58dcbe4-a692-467f-09a0-94172434ed00//width=40,height=40`  
but the server returned [HTTP CODE 403](https://en.wikipedia.org/wiki/HTTP_403), resulting in an `IOException` being raised (you can think of exceptions as kinds of "errors" that can be handled by a program).

If this failure to fetch an image really did result in a crash, then if I were an Essential developer, I'd make sure I place error-handlers next time, so a crash don't take place. So in other words, if that was really a crash, you should probably report it to Essential developers.

### -
Anyways, thanks again for reporting this bug, and have a great day!

**Comment by xxxkingxl** [comment]
It didn't crash, but I added the console log, maybe it helps?!
Thanks for letting me know about this:
`After looking into the crash report, it appears that the following line of code
gg.essential.gui.screenshot.providers.CloudflareImageProvider.loadImage(CloudflareImageProvider.kt:54)
was executed (by I assume "essential"), and it attempted to fetch an image from the internet, as seen here
java.io.IOException: Server returned HTTP response code: 403 for URL: https://imagedelivery.net/W9K_l6ndK9x4x8m3rurakg/e58dcbe4-a692-467f-09a0-94172434ed00//width=40,height=40
but the server returned [HTTP CODE 403](https://en.wikipedia.org/wiki/HTTP_403), resulting in an IOException being raised (you can think of exceptions as kinds of "errors" that can be handled by a program).`
it doesn't give me issues now, but maybe later. I will look in to that issue in my modpack
