### ISSUE TITLE
tcdc dependency in 1.21 is not optional

### ISSUE THREAD

**Issue by MeeniMc** [TheCSMods/mc-better-stats#121]
### Question

In prior versions (1.20.6 or older) the TCDC dependency was optional. It now crashes on launch (fabric resolver) when TCDC is not installed. I'd prefer it to remain optional, if possible.

**Comment by TheCSDev** [comment]
Hello, and thank you for your issue report!

I apologise for inconveniencing you, as this is currently intentional. I have left the info and reasons about this change in the changelog. Basically TCDC was always a dependency, but I've gone around that by embedding it into the mod (in other words, TCDC was inside of BSS the whole time), but this time they have been separated. With the reasons mentioed in the changelog in mind, my hope was that most launchers would hopefully mitigate the inconvenience, as they're programmed to automatically download dependencies. However I still see and understand your point.  
If possible, I may revert this change in the future.

Right now my biggest worry is people who don't use launchers, as they have to manually download TCDC and Fabric API, which is very inconvenient. So I'm hoping I could someday mitigate this by getting Fabric API out of the picture *tho that'd require me figuring some stuff out on my own instead of having Fabric API do it for me).

**Comment by MeeniMc** [comment]
Thanks for what you do with this mod, sorry I missed the changelog item.

**Comment by otter501** [comment]
the dependency for TCDC is only on the modpage, but not in the modrinth dependencies, so launcher don't know to install TCDC

**Comment by TheCSDev** [comment]
> the dependency for TCDC is only on the modpage, but not in the modrinth dependencies, so launcher don't know to install TCDC

Hello. I have just checked, and this does not appear to be the case as far as I can see. Aside from it being named in the mod description, I have made sure to also list it as a dependency in each version file as well, as seen on
<details>
    <summary>this image (click here to view it)</summary>
    <img src="https://github.com/TheCSMods/mc-better-stats/assets/66475965/a441fc0b-94c7-46d2-a65a-adeb7a17ecbd"/>
</details>

When clicking install only on BSS in the modrinth launcher, the other two dependencies also seem to appear as well, as intended;
<details>
    <summary>a screenshot (click here to view it)</summary>
    <img src="https://github.com/TheCSMods/mc-better-stats/assets/66475965/fd2980fe-474f-49da-a645-fcf86033442c"/>
</details>

#

If his is not the case for you, then that is unintentional, as I would like to make 100% sure launchers are able to properly install all dependencies automatically.  
Feel free to let me know what launcher you are using and what version of BSS you were attempting to install when that issue happened (Note that for BSS versions older than v3.11, it is not required to install TCDC).

**Comment by MeeniMc** [comment]
It doesn't check dependencies when you UPDATE a mod using Prism, but it does download TCDC when you INSTALL the mod.

**Comment by otter501** [comment]
it seems to be an issue with the mod manager I am using, so all good on your part

**Comment by TheCSDev** [comment]
> It doesn't check dependencies when you UPDATE a mod using Prism, but it does download TCDC when you INSTALL the mod.

If this is the case, then I was not aware of this. I hope this did not end up inconveniencing people too much, as I assume this means a bunch of people had to deal with a crash report due to a missing dependency.

Thanks for informing me. May still be useful to know for future reference.
