### ISSUE TITLE
I can't see the player badges

### ISSUE THREAD

**Issue by FOgGyWw-W** [TheCSMods/mc-better-stats#136]
### Question

I would like to ask a question regarding the player badges. I have install BSS and TCDcommons but I can't seem to see the player badges on the statistic screen
![Untitled](https://github.com/user-attachments/assets/61b51f30-d8fe-48f1-84ed-49f3538ec507)

**Comment by TheCSDev** [comment]
Hello, and thanks for the question.  
Apologies for taking so long to respond. I forgot about this issue even being opnen, that is, until I just randomly saw it again.

The reason you cannot see player badges is because in the newer versions of this mod, they are disabled by default.  
If you'd like to re-enable them, please refer to the [TCDCommons API configuration article](https://thecsdev.com/docs/tcdcommons/configuring-v3/). There, you will see instructions on how to configure **TCDCommons API**, and thus enable the player badges.
