### ISSUE TITLE
Resource pack support for the buttons in statistics screen

### ISSUE THREAD

**Issue by JustLetterV** [TheCSMods/mc-better-stats#29]
It would be nice to be able to change how buttons look with resource packs :)

**Additional context**
These buttons:
![image](https://user-images.githubusercontent.com/75657829/211983323-c3816104-3ffb-405f-b557-1ded3331a0c4.png)
![image](https://user-images.githubusercontent.com/75657829/211983959-419ce4ad-e2be-4ef5-84f3-43065797f253.png)

**Comment by TheCSDev** [comment]
Hello. The mod uses a completely different UI system where widgets buttons are actually scalable and flexible (their size can change to anything), unlike in Vanilla where buttons and other widgets can only be 20px in height. Because of this, I had to create my own textures for the UVs instead of using the Vanilla ones. I was however, thinking of swapping the textures for those two buttons back to Vanilla textures as those buttons are 20px in height anyways.

Changing the textures of those two buttons is possible. The textures belong to [TCDCommons](https://github.com/TheCSMods/mc-tcdcommons/tree/main/tcdcommons-1.19.2/src/main/resources/assets). Just download them from the linked `assets` folder, and make a resource pack out of that. Another place you can find the default textures is in the jar file. Just download any TCDCommons jar file, and open it as a zip. You should find the assets folder in there.
