### ISSUE TITLE
[1.19.2 2.2 Fabric]  Crash on Mob Stats

### ISSUE THREAD

**Issue by itsdinkd** [TheCSMods/mc-better-stats#32]
**Describe the bug**
Added this mod to my pack, AQM2. As I went to the Mobs section and scrolled down to see all mobs, the game crashed. This was on a local test server. Client crashed. Server showed a netty pipeline error.

**To Reproduce**
1. Download AQM2
2. Add this mod
3. Go into local server (or possibly single player)
4. View Mobs stat section
5. scroll down to bottom
6. crash

Logs; https://mclo.gs/EMT6dqT

**netty error in server**
![image](https://user-images.githubusercontent.com/35115304/216511745-4c767e5b-7bb9-4a45-bb82-cbd154791f05.png)

**Comment by TheCSDev** [comment]
Hello. Thanks a lot for the bug report.  
The netty error stack trace you have provided is not the actual cause of the crash. Thankfully you provided the full logs, so the actual cause is this:
```
Time: 2023-02-02 20:18:26
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_[8](https://mclo.gs/EMT6dqT#L8)[9](https://mclo.gs/EMT6dqT#L9)7.method_23169(net.minecraft.class_1297, float)" because "$$9" is null
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher.java:134)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.method_29977(InventoryScreen.java:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:[11](https://mclo.gs/EMT6dqT#L11)71)
	at net.minecraft.client.gui.screen.ingame.InventoryScreen.drawEntity(InventoryScreen.java:152)
	at io.github.thecsdev.tcdcommons.api.client.gui.other.TEntityRendererElement.render(TEntityRendererElement.java:166)
```
Looking at the crash stack trace, this appears to be an issue with a modded entity being rendered on the screen. This also appears to be the most common cause of crashes that occurs thanks to other mods. It essencially boils down to modded mobs being programmed in a way that "assumes" the mob always exists in a specific state, and such mods never take into account that their mobs may get rendered on the screen locally, hence a crash taking place.

Now what I need to do is figure out which mod it is that is causing Better Stats to crash. According to the crash report, you might be using a mod pack, given the amount of mods you have installed, so spotting the mod that does this may be a bit difficult.

If you are using a mod pack, please do let me know which one it is. In the meantime, I will try to figure out which mod it is that is crashing your game, after which I will try to patch it.

**Comment by TheCSDev** [comment]
Oh I somehow totally missed the part where you said AQM2. I am working on a path right now, so hopefully it works.

**Comment by TheCSDev** [comment]
I think I managed to patch the issue. I tested the patch on the AQM2 mod pack, and didn't encounter any issues, so hopefully it works out. I will now go ahead and publish the patch.

Once I publish the patch, please do let me know if it works, or you can just close this issue if the patch does work.  
Thanks again for reporting this bug, and have a great day.

**Comment by itsdinkd** [comment]
Wow great! Super fast! Will do, thanks!

**Comment by TheCSDev** [comment]
You're welcome. I will now close the issue since it has been resolved. If you do end up encountering it again, feel free to let me know so I can re-open it.
