### ISSUE TITLE
[BSS (fabric-1.18.2) - v2.6.1] Incompatible with Quilt due to FAPI / QFAPI Version Difference

### ISSUE THREAD

**Issue by PlayfulPiano** [TheCSMods/mc-better-stats#47]
**Describe the bug**
The latest version of the Quilted Fabric API is based on Fabric API version 0.67, whereas the latest version of BSS uses a Fabric API version past that. This causes worlds to be unable to get created or loaded, and is related to the class "net.fabricmc.fabric.impl.resource.loader.BuiltinModResourcePackSource".

**Comment by TheCSDev** [comment]
Altho I don't use Quilt and only ever focus on Fabric, I think I understand what you're trying to report.

So from here, I saw two possible solutions:
- One would be to wait and hope that one day "Quilted Fabric API" gets ported to the lastest "Fabric API" version,
- And the other would be to publish another update that undoes the latest update, which is counter intuitive, given that one of the main purposes of the latest update was to keep the dependecies up to date as well.

So given that I don't like either of those two for now, I have decided to do a "workaround". I published [an additional file](https://www.curseforge.com/minecraft/mc-mods/better-stats/files/4520279) that has no embedded libraries, and instead allows you to manually install whichever versions of "Fabric API" and "Architectury API" you choose. Just keep in mind that because this mod depends on "TCDCommons", you will have to install [this file specifically](https://curseforge.com/minecraft/mc-mods/tcdcommons/files/4520268) as well.

**Comment by TheCSDev** [comment]
Also, in the meantime, do you happen to know if Quilted Fabric API plans on continuing working on 1.18.2 or not? I assume you don't, but if they don't plan to, then perhaps I could reverse the latest update only for 1.18.2 in the next release for this mod.

Have a great day as well.

**Comment by PlayfulPiano** [comment]
I believe they no longer support 1.18.2 so yeah it's staying at 0.67.

**Comment by TheCSDev** [comment]
I have just finished uploading `v2.9(.1)`, which will be the last update I make for `< 1.20` Minecraft releases. So yeah, I guess time has come for me too to move on from `1.18.2`... Unfortunately I haven't resolved this issue yet, however I did upload a "clean" version/jar file you could use. The "clean" files doesn't have `Fabric API` embedded into it, so you can download whichever `Fabric API` version you want alongside it. You can find it on CurseForge in the "Additional files" section, as well as on this repository in the "Releases" section.

In case you're wondering why I'm moving onto `1.20` once I port to that version, and not coming back to older versions; It's because the update completely broke my mods. Like, it is broken beyond broken. The term "broken" feels like an understatement. Basically a whole bunch of GUI and probably other stuff got re-written, and this mod relies on that stuff, so yeah.. Once I finally manage to port, for me it'd cost too much time and effort to keep maintaining older versions.

So, I'm gonna close this issue now and, have a great day!
