### ISSUE TITLE
[v2.7.2+fabric] Visual bug on the BSS options screen. Items and entities clipping with GUI elements.

### ISSUE THREAD

**Issue by QueenUlyana** [TheCSMods/mc-better-stats#52]
**Describe the bug**
The interface is crumbling. The selection settings are not saved.

**To Reproduce**
1. Open "Statistics".
2. Select "A Balanced Diet" or "Monster Hunted" in the filter.
3. Click "Options" at the bottom and you will see the interface crumbling.
4. If you select the parameters you want in the filter, they will reset after exiting the statistics.

I need the settings I selected to be saved, not discarded.
![2023-05-26_18 32 22](https://github.com/TheCSMods/mc-better-stats/assets/83131824/e79f79f8-5b23-4f6d-9b88-d7216a24c073)
![2023-05-26_18 32 17](https://github.com/TheCSMods/mc-better-stats/assets/83131824/6b6242a8-dc5d-49ff-ab31-100106c29ce6)
![2023-05-26_18 32 10](https://github.com/TheCSMods/mc-better-stats/assets/83131824/a2062c89-4673-426e-a2e2-d92091bbd042)
![2023-05-26_18 32 05](https://github.com/TheCSMods/mc-better-stats/assets/83131824/93f16ead-26ed-4c80-80b8-4cc9d4a61767)

**Comment by TheCSDev** [comment]
Yeah, I was aware of this visual bug taking place as I was developing the options menu. Thanks for reporting it tho. I didn't bother fixing it due to how Minecraft handles rendering of certain UI elements, altho I might get to fixing it eventually however.

### Technical explaintation in case you're interested
Basically, not all UI elements are "flat", and some are "3D" shapes. Those things include UI mobs and items. Because some things are "3D", drawing a "2D flat" plane on top of a 3D object can cause "clipping". The only way to resolve this would be to modify the "Z index" of the options UI further towards the "camera". One small issue here is that there's obviously a limit as to how much you can offset the "Z index" by, and going too much would "go past the camera", causing the "camera" to end up not rendering it at all.. (I know this is too technical and complicated). Dealing with items could be simpler, as their size is largely the same, but mob's sizes vary a lot, and to make up for that, I might end up having to offset the "Z index" of the options GUI by too much, which as I mentioned, causes futher visual bugs. And on top of all that, Minecraft on its own already puts 

### -
If only Minecraft rendered "3D models" on the screen as "2D images", that'd be cool. Anyways, I could try and tackle items in the future, not sure about entities. So.. I guess don't swith to those tabs in the meantime if the "3d models" are blocking your view.
Anyways, thanks again for the bug report, and have a great day!

**Comment by QueenUlyana** [comment]
> Yeah, I was aware of this visual bug taking place as I was developing the options menu. Thanks for reporting it tho. I didn't bother fixing it due to how Minecraft handles rendering of certain UI elements, altho I might get to fixing it eventually however.
> 
> ### Technical explaintation in case you're interested
> Basically, not all UI elements are "flat", and some are "3D" shapes. Those things include UI mobs and items. Because some things are "3D", drawing a "2D flat" plane on top of a 3D object can cause "clipping". The only way to resolve this would be to modify the "Z index" of the options UI further towards the "camera". One small issue here is that there's obviously a limit as to how much you can offset the "Z index" by, and going too much would "go past the camera", causing the "camera" to end up not rendering it at all.. (I know this is too technical and complicated). Dealing with items could be simpler, as their size is largely the same, but mob's sizes vary a lot, and to make up for that, I might end up having to offset the "Z index" of the options GUI by too much, which as I mentioned, causes futher visual bugs.
> 
> ### -
> If only Minecraft rendered "3D models" on the screen as "2D images", that'd be cool. Anyways, I could try and tackle items in the future, not sure about entities. So.. I guess don't swith to those tabs in the meantime if the "3d models" are blocking your view. Anyways, thanks again for the bug report, and have a great day!

What about saving the filter settings? Will you make it so that they are saved?

**Comment by TheCSDev** [comment]
Oh, sorry I missed that part.
If by saving, you mean actually like storing the settings on the hard drive, then not for now. There's no need to implement such a feature only for  "Debug mode", which technically isn't even a "setting".

I added the config screen in case I ever end up needing it for actual configs (and so I can have a place for the "Debug mode"), and I then added "Debug mode" so I can check world seed hashes, and later chose to keep it in the mod in case someone else ever wanted it.

Because for now I never implemented any like actual configs that control the mod behavior, I just didn't wanna bother with IO operations (aka saving/loading configs on the drive).

**Comment by TheCSDev** [comment]
Relying again because I missed the word "filters" in your question (sorry again). As for those, I never had plans on saving them.

**Comment by QueenUlyana** [comment]
> Relying again because I missed the word "filters" in your question (sorry again). As for those, I never had plans on saving them. Edit: Just got an idea, maybe I can finally implement a config setting that allows filters to be saved. The reason I didn't save filters is because I saw having to change filters back and forth every time when opening the BSS screen as inconvenient.

I will wait for it in the update. You can make an option that will toggle whether to save the filter settings. It would be convenient for everyone.
