### ISSUE TITLE
[v2.9+any] Mobs on the mob statistics tab don't render

### ISSUE THREAD

**Issue by Rozbiynk** [TheCSMods/mc-better-stats#59]
### What happened?

![изображение](https://github.com/TheCSMods/mc-better-stats/assets/95433246/ef5d1cda-2581-45b5-9573-b2f4f8701fb3)

### Steps to reproduce

Open mob category
See. 

### Relevant log output or crash report

```shell
Edit by TheCSDev: Removed the logs link as it contained potentially sensitive information that could compromise privacy.
```

### Other installed mods

Edit by TheCSDev: I took down the mod list link because of a major security issue.

### Code of Conduct

- [X] I agree that if the issue is regarding a crash, I gave the logs and the crash report.
- [X] I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.

**Comment by Rozbiynk** [comment]
what launcher do you use?

**Comment by TheCSDev** [comment]
Vanilla launcher, with FabricMC installed. I tried QuiltMC as well.

**Comment by Rozbiynk** [comment]
https://www.mediafire.com/file/4h06hqe21q3kcfl/Lantern.zip/file

**Comment by TheCSDev** [comment]
Thanks.
If I find the causing mod and I'm able to patch it, will likely do it for 1.20 only.
I wrote more info as to why in the 2nd paragraph of [my #47 comment](https://github.com/TheCSMods/mc-better-stats/issues/47#issuecomment-1591741825).

**Comment by TheCSDev** [comment]
Yo! @Rozbiynk. You need to take down that `MediaFire` file you published, like.. asap, as in like.. ***urgently***. I know you wanted to provide a mod list, but you uploaded your private information and login credentials alongside the mod-pack. When I ran the game, I was able to quickly log-into your account via some sort of account switcher mod.

In the future, please be more careful with how you handle your private info, especially account login credentials.
I will remove this link off of here for you, ***but***, I still highly recommend you take down that file off of `MediaFire`, because anyone with that link can access all the stuff on there,

**Comment by TheCSDev** [comment]
Oh and, it should go without saying:
***Change your Microsoft/Mojang account password immediately.*** That way, in case anybody got access to your account(s), will then lose that access.

**Comment by TheCSDev** [comment]
In the meantime, given the nature of this bug, I will close it as not planned for now. Maybe some day I fix it. Same goes for the other bug report.
