### ISSUE TITLE
[v3.0.0+fabric-1.20.1] Game Menu Crash

### ISSUE THREAD

**Issue by kyber-6** [TheCSMods/mc-better-stats#73]
### What happened?

I pressed the statistics button in the game menu and the game crashed immediately.

### Steps to reproduce

1. Go to game menu
2. Press Statistics
3. Game crashes

### Relevant log output or crash report

```shell
- Crash report: https://crashy.net/53fd9660-25d6-4a3a-b85f-ea98553f9f7b
```

### Other installed mods

Unreleased 1.20.1 version of Fantasy MC.

### Code of Conduct

- [X] I agree that if the issue is regarding a crash, I gave the logs and the crash report.
- [X] I agree that I will be available later for any follow-up questions to help diagnose and resolve the issue.

**Comment by TheCSDev** [comment]
Hello!
Thanks for the crash report. After checking the code, it appears the crash is caused by a general stat missing an ID. Given all Vanilla stats have proper IDs, I can only assume a modded stat is registered that did not have an ID at the moment of the crash. In other words, technically an incompatibility. I'll try to look into it further once I get the time to. Thanks again, and have a great day!

**Comment by TheCSDev** [comment]
Hello again.
I just released a patch, and hopefully it fixes the issue you are encountering. I noticed another compatibility issue in the meantime as well, and patched that one too.

You can [download the release here](https://github.com/TheCSMods/mc-better-stats/releases/tag/v3.1).
Unfortunately CurseForge randomly decided to pick on me and place most files I attempt to upload "Under manual review", and those reviews can take days to weeks to complete given how slow their reviewers are. Until then, there's the Releases page on GitHub.

If you experience further issues, feel free to let me know. Have a great day!

**Comment by kyber-6** [comment]
Great! Thanks for the quick response.
