### ISSUE TITLE
[v3.3] Hardcored Translations.

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [TheCSMods/mc-better-stats#84]
### Description

These strings should be available to be translated, not to mention they actually should be translated as well.

![image](https://github.com/TheCSMods/mc-better-stats/assets/51203385/fe8f4a43-4f30-4a85-8352-633f1f4c5b7d)
![image](https://github.com/TheCSMods/mc-better-stats/assets/51203385/1843112b-1d72-43d8-92a1-a424c2b18ae5)

### Steps to reproduce

1. Go to Statistics.
2. You are here! But if You want to see "Value:", then You should to hover on any stat.

**Comment by TheCSDev** [comment]
Oh the one's you've shown, not all of them are hard-coded.
- UUID - hard-coded
- Seed (SHA-256) - hard-coded
- Player badges - not hard-coded: `tcdcommons.api.badge.playerbadge.plural`
- Value - not hard-coded: `betterstats.api.client.gui.stats.widget.generalstatwidget.value`

As for the numeric value, it's intentional. It's the "un-formatted" literal integer value of the general stat. So the stat widget itself shows the "formatted" value (for example 1m) whereas the tooltip shows the literal unformatted value (for example 100, which means 100cm aka 1m)

**Comment by TheCSDev** [comment]
Oh and by the way, that literal unformatted value integer for general stats tooltip and the tooltip itself are there to aid with the `/statistics` command. Bastially, the game in the background handles raw values, and so when you use the `/statistics` command, you have to supply raw unformatted values as well. That tooltip right there shows you the stat ID and its current "raw"/"unformatted" value.

So you can do like `/stats edit @s minecraft:custom minecraft:walk_one_cm set 85012`, where hte 85012 is the literal number in centimeters. which translates to 0.85km when formatted

**Comment by TheCSDev** [comment]
All done. Translations for those will be available in `v3.4` that I am about to publish on CF and Modrinth.
