### ISSUE TITLE
[Suggestion] update 1.19.2 forge version of Better Statistics Screen

### ISSUE THREAD

**Issue by Qian-F** [TheCSMods/mc-better-stats#85]
### What is this suggestion for?

Mod Itself

### Suggestion

The 1.19.2 version of this mod is outdated, and I believe players will prefer it to be synchronized with the fabric version.

### Code of Conduct

- [X] I agree that I will be available later for any follow-up questions to help with implementing the suggested thing.

**Comment by TheCSDev** [comment]
Hello, and thank you for your suggestion.

While I appreciate this suggestion and understand why you and probably a lot more people would want me to do this, this however, is not in my plans, and will likely never happen. There are several reasons for this.
- First of all, I primarily focus on the latest versions of the game. In the past, I used to maintain multiple versions, and it was somewhat bearable at the very least. Then Mojang came along and was like, "Hey, just so you all know, we're now gonna be introducing new features and changes in 1.X.X versions as well, and not just the yearly 1.X versions", effectively making game-breaking change's to the game's code like literally every single update in the past few months. This effectively turned the "bearable" into "unbearable". I mean, just have a look at how long it took to write the first alpha release of v3.0 that actually properly addresses Mojang's changes to the game's code (and some of my messy code as well):
![image](https://github.com/TheCSMods/mc-better-stats/assets/66475965/0a1884b6-5b5a-4072-b3d4-79be0a22202e)
It was a few months gap, of me working constantly every day. There's just simply no way I am doing something like that ever again, just so a backport to older (and possibly less played) versions can exist, especially for a mod-loader I don't even work with.
- And finally, the second primary reason; I only work with FabricMC. Sure, I did write a Forge version once in the past, that's true. I originally planned to support both loaders, but that turned out to be something that's way too hard and unmaintainable for me. I also have little to no experience with Forge modding, so that port I put together that you saw of 1.19 was very poorly executed and the code was a straight-up mess. I basically aimed for making it "at least functional", and some features I failed to port as well, as I didn't know how to. On top of that, making Forge ports for each release doubles the development time, so just imagine those months I've shown earlier, but x2.5 (the .5 because I have no Forge experience). As far as I know, there are solutions that aim to aid in this, such as [Architectury API](https://www.curseforge.com/minecraft/mc-mods/architectury-api) and [Architectury Loom](https://github.com/architectury/architectury-loom), of which the Loom one doesn't even support my modding environment (aka IDE (Eclipse IDE)), and making switches to other IDEs that do support those and then having my mod depend on the Architetury mod despite wanting to be "independent" and then on top of that having to spend extra time and effort on a platform I don't work with is something I am simply not comfortable with.

Again, I understand why you suggested this, and I too found myself a lot in those situations where I see a mod I love and I want it ported over to the version and loader I play with, but I also hope you can understand these two points I brought up as well. It's something many if not most mod devs. have to deal with.

With that, thanks a lot again for the suggestion, and have a great day!

**Comment by Qian-F** [comment]
Thank you for your detailed response. This is the first time I have ever received such a caring and patient reply! I understand your situation and the challenges you are currently facing. Whether or not it's possible to transplant a newer version depends on the degree of difference between each version's code. What I want to say is, be yourself! Thank you for taking the time to tell me all these things! I will continue to follow your mods and projects, enjoying every day in Minecraft!

**Comment by TheCSDev** [comment]
Thank you so much! I appreciate it.
