### ISSUE TITLE
[v2.2.2+forge-1.18.2] Half of the screen is not rendering, and stats entries are not showing up properly

### ISSUE THREAD

**Issue by Sevenyine** [TheCSMods/mc-better-stats#98]
### Question

System: macOS Sonoma 14.0 (23A344) M2

My statistic screen is not showing enough entries, and also the canvas is only half-screen. No buttons are shown, such as the 'Show Vanilla Stats' button.

### Full screen

<img width="1470" alt="image" src="https://github.com/TheCSMods/mc-better-stats/assets/65720409/1209accb-f023-445d-83d6-e0c274c2305f">

### Window

<img width="854" alt="image" src="https://github.com/TheCSMods/mc-better-stats/assets/65720409/432ddf85-96eb-4287-a09d-f5e93e415b20">

### Mods menu

<img width="1470" alt="image" src="https://github.com/TheCSMods/mc-better-stats/assets/65720409/3137bfe4-b13f-480e-9290-46d44a8e75f9">

**Comment by TheCSDev** [comment]
Hello.

This issue appears to be related to #38. I already tried investigating the potential causes for #38, and was unsuccessful in finding a cause. For obvious reasons, it is not intended for only half the screen to be visible. My best guess if that it may have something to do with `Rubidium`, if you are using that mod. Given I have little to no forge modding experience either, and older versions (especially forge) are not maintained anymore, I will unfortunately not be able to resolve this.

Given this issue is a duplicate of #38, and I had no choice but to close #38 as "Not planned", I will unfortunately have to do the same here. I am sorry in advance for whatever that bug/incompatibility may be.

**Comment by Sevenyine** [comment]
Understood and sorry for the duplication.
