### ISSUE TITLE
Request: update to 1.20.4

### ISSUE THREAD

**Issue by jurohn** [TheCSMods/mc-better-stats#99]
### What is this suggestion for?

Mod Itself

### Suggestion

Request: update to 1.20.4

### Code of Conduct

- [X] I agree that I will be available later for any follow-up questions to help with implementing the suggested thing.

**Comment by TheCSDev** [comment]
Hello!
I do in fact plan on porting to 1.20.4, which will be done soon hopefully.

Right now, I am waiting for REI to port to 1.20.4, because, even though installing REI is optional for this mod itself, the source code of this mod uses REI's APIs, hence why I need REI 1.20.4 first. In the meantime I am working on another feature in my own TCDCommons API mod.

![image](https://github.com/TheCSMods/mc-better-stats/assets/66475965/5c3f3bb6-28dc-4275-a14f-ad4fb1f5e338)

**Comment by TheCSDev** [comment]
Actually, it appears I didn't notice REI 1.20.4 was already published, but on CurseForge, and the API is available on gradle now. This means I can finally start working on the port. Thanks for the reminder!

**Comment by TheCSDev** [comment]
Hello again.
I have ported the mod to `1.20.4` just now, and published a copy of the port on the [GitHub Releases page](https://github.com/TheCSMods/mc-better-stats/releases/tag/v3.6). Please read the additional note I added to the changelogs by the way. In the meantime, I will focus on publishing the release on other platforms.
Have a great day!

**Comment by jurohn** [comment]
Thank you sir!
